CREATE TABLE IF NOT EXISTS financas.TB_LANCAMENTO(
    ID_LANCAMENTO SERIAL PRIMARY KEY,
    DS_LANCAMENTO VARCHAR(255) NOT NULL,
    MES_LANCAMENTO INTEGER NOT NULL,
    ANO_LANCAMENTO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    VALOR_LANCAMENTO DECIMAL(10, 2) NOT NULL,
    DT_CADASTRO_LANCAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_LANCAMENTO INTEGER(1) NOT NULL,
    STATUS_LANCAMENTO INTEGER(1) NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES financas.TB_USUARIO(ID_USUARIO)
);

COMMENT ON TABLE financas.TB_LANCAMENTO IS 'Tabela de lançamentos';

COMMENT ON COLUMN financas.TB_LANCAMENTO.DS_LANCAMENTO IS 'Descrição do lançamento';

COMMENT ON COLUMN financas.TB_LANCAMENTO.MES_LANCAMENTO IS 'Mês do lançamento';

COMMENT ON COLUMN financas.TB_LANCAMENTO.ANO_LANCAMENTO IS 'Ano do lançamento';

COMMENT ON COLUMN financas.TB_LANCAMENTO.ID_USUARIO IS 'ID do usuário';

COMMENT ON COLUMN financas.TB_LANCAMENTO.VALOR_LANCAMENTO IS 'Valor do lançamento';

COMMENT ON COLUMN financas.TB_LANCAMENTO.DT_CADASTRO_LANCAMENTO IS 'Data de cadastro do lançamento';

COMMENT ON COLUMN financas.TB_LANCAMENTO.TIPO_LANCAMENTO IS 'Tipo do lançamento';

COMMENT ON COLUMN financas.TB_LANCAMENTO.STATUS_LANCAMENTO IS 'Status do lançamento';