insert into financas.TB_LANCAMENTO (DS_LANCAMENTO, MES_LANCAMENTO, ANO_LANCAMENTO, ID_USUARIO, VALOR_LANCAMENTO, TIPO_LANCAMENTO, STATUS_LANCAMENTO) values ('Salário', 1, 2021, 1, 5000.00, 1, 1);
insert into financas.TB_LANCAMENTO (DS_LANCAMENTO, MES_LANCAMENTO, ANO_LANCAMENTO, ID_USUARIO, VALOR_LANCAMENTO, TIPO_LANCAMENTO, STATUS_LANCAMENTO) values ('Aluguel', 1, 2021, 1, 1000.00, 2, 1);
insert into financas.TB_LANCAMENTO (DS_LANCAMENTO, MES_LANCAMENTO, ANO_LANCAMENTO, ID_USUARIO, VALOR_LANCAMENTO, TIPO_LANCAMENTO, STATUS_LANCAMENTO) values ('Salário', 1, 2021, 2, 5000.00, 1, 1);
insert into financas.TB_LANCAMENTO (DS_LANCAMENTO, MES_LANCAMENTO, ANO_LANCAMENTO, ID_USUARIO, VALOR_LANCAMENTO, TIPO_LANCAMENTO, STATUS_LANCAMENTO) values ('Aluguel', 1, 2021, 2, 1000.00, 2, 1);
insert into financas.TB_LANCAMENTO (DS_LANCAMENTO, MES_LANCAMENTO, ANO_LANCAMENTO, ID_USUARIO, VALOR_LANCAMENTO, TIPO_LANCAMENTO, STATUS_LANCAMENTO) values ('Salário', 1, 2021, 3, 5000.00, 1, 1);
insert into financas.TB_LANCAMENTO (DS_LANCAMENTO, MES_LANCAMENTO, ANO_LANCAMENTO, ID_USUARIO, VALOR_LANCAMENTO, TIPO_LANCAMENTO, STATUS_LANCAMENTO) values ('Aluguel', 1, 2021, 3, 1000.00, 2, 1);
