spring:
  application:
    name: financa-api
  datasource:  
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/financa
     username: financa
     password: financa123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/financa
    user: financa
    password: financa123
